/**
 * The canonical basis of an algebra: every blade in storage order, with its
 * grade and generator indices. Owned values carry their basis so inspection,
 * grade access, and blade access never assume one algebra's layout.
 *
 * Blades are ordered by grade, then lexicographically by strictly increasing
 * generator index, as every convention specification requires. The scalar
 * blade is named `e`; other blades are `e` followed by their indices.
 */
export type BasisBlade = Readonly<{
  name: string
  grade: number
  indices: readonly number[]
}>

export type AlgebraBasis = Readonly<{
  blades: readonly BasisBlade[]
  generatorIndices: readonly number[]
  maxGrade: number
}>

/** Builds the canonical basis generated by the given ascending generator indices. */
export function createAlgebraBasis(generatorIndices: readonly number[]): AlgebraBasis {
  const generators = [...generatorIndices]
  if (generators.some((index, position) => position > 0 && index <= generators[position - 1])) {
    throw new RangeError('Generator indices must be strictly increasing.')
  }
  const blades: BasisBlade[] = []
  for (let grade = 0; grade <= generators.length; grade += 1) {
    for (const indices of combinations(generators, grade)) {
      blades.push({ name: bladeName(indices), grade, indices })
    }
  }
  return Object.freeze({
    blades: Object.freeze(blades),
    generatorIndices: Object.freeze(generators),
    maxGrade: generators.length,
  })
}

function combinations(items: readonly number[], size: number): number[][] {
  if (size === 0) return [[]]
  return items.flatMap((item, position) =>
    combinations(items.slice(position + 1), size - 1).map((rest) => [item, ...rest]),
  )
}

export function bladeName(indices: readonly number[]): string {
  return indices.length === 0 ? 'e' : `e${indices.join('')}`
}

/** Storage index of a canonical blade name, or `-1` when the basis has none. */
export function bladeIndex(basis: AlgebraBasis, name: string): number {
  return basis.blades.findIndex((blade) => blade.name === name)
}

export type PermutedBlade = Readonly<{ index: number; sign: 1 | -1 }>

/**
 * Resolves a blade written with its generator indices in any order, such as
 * `e21` for `-e12`, to its canonical storage index and permutation sign. A
 * repeated or unknown generator, or a name that is not a blade, yields `null`.
 */
export function permutedBlade(basis: AlgebraBasis, name: string): PermutedBlade | null {
  if (name === 'e') return { index: 0, sign: 1 }
  if (!/^e\d+$/.test(name)) return null
  const indices = [...name.slice(1)].map(Number)
  if (new Set(indices).size !== indices.length) return null
  if (indices.some((index) => !basis.generatorIndices.includes(index))) return null
  const sorted = [...indices].sort((left, right) => left - right)
  const index = bladeIndex(basis, bladeName(sorted))
  if (index < 0) return null
  return { index, sign: permutationSign(indices) }
}

function permutationSign(indices: readonly number[]): 1 | -1 {
  let swaps = 0
  for (let left = 0; left < indices.length; left += 1) {
    for (let right = left + 1; right < indices.length; right += 1) {
      if (indices[left] > indices[right]) swaps += 1
    }
  }
  return swaps % 2 === 0 ? 1 : -1
}
